# NumPy Basics

In [4]:
# Importing
import numpy as np

## Creation of np.array

In [5]:
# Creation of np.array from list
list_a = [1, 2, 3]
a = np.array(list_a)
print(a)
print(type(a))
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [6]:
# 2D array
list_b = [[1, 0, 0],
          [0, 1, 0],
          [0, 0, 1]]
b = np.array(list_b)
print(b)
print(type(b))
print(b.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
<class 'numpy.ndarray'>
(3, 3)


In [7]:
# To create arrays of 0s and 1s
zero_array = np.zeros((2,3))
one_array = np.ones((3,4))
print(zero_array)
print(one_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
# Generating random numbers
c = np.random.randint(low=1, high=10, size=(3,3))
d = np.random.rand(8, 3)
e = np.random.random_sample((3, 4))
print(c,"\n")
print(d,"\n")
print(e)

[[9 8 7]
 [3 8 8]
 [3 5 1]] 

[[0.43316915 0.39019461 0.53932419]
 [0.45744171 0.35404129 0.98187238]
 [0.99262702 0.92787156 0.85248209]
 [0.25554108 0.60021572 0.49762327]
 [0.34820725 0.67143493 0.84471567]
 [0.70482935 0.52758602 0.72327779]
 [0.52220925 0.6628683  0.49024165]
 [0.57561436 0.07551755 0.92749403]] 

[[0.1201912  0.14552007 0.1414356  0.16633795]
 [0.21178899 0.72449327 0.21034769 0.21292948]
 [0.82858444 0.90630802 0.09364073 0.28170537]]


## Reshaping arrays

In [11]:
# Reshaping arrays into required shape
d_1 = np.reshape(d, newshape=(6, 4))
# In order to reshape from 8x3 to 6x4, size can also be mentioned as (6, -1)
# The remaining factor (in place of -1) is automatically computed
d_2 = d.reshape((6, -1))
print(d_1,"\n")
print(d_2,"\n")
print(d_1 == d_2)

[[0.22863248 0.66266577 0.59715591 0.52274789]
 [0.43124092 0.95540874 0.87424437 0.77739404]
 [0.71470014 0.11297335 0.7163538  0.95874408]
 [0.62473186 0.32628418 0.19421086 0.73890301]
 [0.74844871 0.1554475  0.2996873  0.41640107]
 [0.9044698  0.0677366  0.79470319 0.47309211]] 

[[0.22863248 0.66266577 0.59715591 0.52274789]
 [0.43124092 0.95540874 0.87424437 0.77739404]
 [0.71470014 0.11297335 0.7163538  0.95874408]
 [0.62473186 0.32628418 0.19421086 0.73890301]
 [0.74844871 0.1554475  0.2996873  0.41640107]
 [0.9044698  0.0677366  0.79470319 0.47309211]] 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [29]:
# Task: Try to reshape the array into a 3D array of shape 2x3x4

d_3 = np.reshape(d, newshape=(2,3,4))

print(d_3)

[[[0.43316915 0.39019461 0.53932419 0.45744171]
  [0.35404129 0.98187238 0.99262702 0.92787156]
  [0.85248209 0.25554108 0.60021572 0.49762327]]

 [[0.34820725 0.67143493 0.84471567 0.70482935]
  [0.52758602 0.72327779 0.52220925 0.6628683 ]
  [0.49024165 0.57561436 0.07551755 0.92749403]]]


## Deletion of elements

In [26]:
# Deletion of rows/columns
d_col_delete = np.delete(d, 1, axis=1)
d_row_delete = np.delete(d, 2, axis=0)
print(d_col_delete.shape)
print(d_row_delete.shape)

(8, 2)
(7, 3)


In [ ]:
# Learn the concepts of axis properly
# Check StackOverflow or NumPy documentation for more details

In [ ]:
# Task: Delete a particular element of array `c`

## Merging Rows or Columns

In [ ]:
# Merging Rows/Columns
merge_rows = np.vstack((c, d))
merge_cols = np.hstack((c, e))

In [ ]:
print(mergeRows)

In [ ]:
print(mergeCols)

In [ ]:
# Task: Try using np.concatenate to perform the above operations

# Aggregate Functions

In [ ]:
# Task: Find the row-wise minimum of the array `c`
# Task: find the column-wise mean of array `d`
# Task: Find the row-wise mean of array `e`
# Task: Find the maximum of all values in the array `c`